trainer:
  accelerator: gpu
  devices: [6]
  accumulate_grad_batches: 2
model:
  class_path: gesture_detection.models.lstm.LSTM
  init_args:
    lr: 0.001
    backbone_lr: 0.001
    weight_decay: 0.0
    batch_size: 32
    small: False