trainer:
  accelerator: gpu
  devices: 1
  accumulate_grad_batches: 2
model:
  class_path: gesture_detection.models.lstm.LSTM
  init_args:
    lr: 0.0001
    backbone_lr: 0.0001
    weight_decay: 0.0
    small: False
data:
  init_args:
    batch_size: 32