seed_everything: true
trainer:
  accelerator: gpu
  strategy:
    class_path: lightning.pytorch.strategies.SingleDeviceStrategy
    init_args:
      device: 0
  devices: 1
  num_nodes: 1
  precision: null
  logger: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.DeviceStatsMonitor
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 1
        save_top_k: -1
  fast_dev_run: false
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
  log_every_n_steps: 10
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 2
  gradient_clip_val: null
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: false
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  class_path: gesture_detection.models.lstm.LSTM
  init_args:
    num_classes: 26
    lr: 0.001
    loss_weight: [0.0195368843784718, 1.0941244726903903, 0.8813780474450368, 1.007289197080042, 1.023535797032946, 1.023535797032946, 0.9915503033756663, 1.0755799901024177, 1.007289197080042, 1.007289197080042, 1.023535797032946, 1.007289197080042, 1.0403150723941417, 1.1133196388779412, 1.007289197080042, 1.0941244726903903, 1.007289197080042, 1.023535797032946, 1.0755799901024177, 1.1538039893825933, 0.9332238149418036, 1.133200346715047, 1.0403150723941417, 1.007289197080042, 1.0755799901024177, 1.133200346715047]
    weight_decay: 0.0
    sample_length: 32
    small: True
data:
  class_path: gesture_detection.datasets.h5dataset.H5DataModule
  init_args:
    dataset_root: "data/h5dataset"
    dataset_info_filename: "nvgesture.hdf5"
    batch_size: 48
    sample_length: 32
    num_workers: 8
    pin_memory: true
